# Automatically adds labels to a pull request.
# https://github.com/actions/labeler

# Labels based on branch name
"type: bug":
  - head-branch: ['^bug/', '^bugfix/']

"type: feature":
  - head-branch: ['^feature/', '^feat/']

"type: maintenance":
  - head-branch: ['^maintenance/', '^techdebt/', '^chore/']

"type: release":
  - head-branch: ['^release/']

# Labels based on files changes
"domain: backend":
- all:
    - changed-files:
        - any-glob-to-any-file:
          - 'src/main/groovy/**/*'
          - 'grails-app/**/*.groovy'
        - all-globs-to-all-files:
          - '!grails-app/taglib/**/*'

"domain: frontend":
- changed-files:
  - any-glob-to-any-file:
    - 'grails-app/taglib/**/*'
    - '**/*.js'
    - '**/*.jsx'
    - '**/*.scss'
    - '**/*.css'
    - '**/*.html'
    - '**/*.gsp'

"domain: devops":
- changed-files:
  - any-glob-to-any-file:
    - '.github/**/*'
    - 'docker/**/*'

"flag: config change":
  - changed-files:
      - any-glob-to-any-file:
          - 'grails-app/conf/**/*'
          - '**/*.gradle'
          - 'package.json'
          - 'package-lock.json'

"flag: schema change":
- changed-files:
  - any-glob-to-any-file:
      - 'grails-app/migrations/**/*'