site_name: OpenBoxes
site_description: OpenBoxes documentation
site_author: Justin Miranda
site_url: https://docs.openboxes.com/en/
repo_url: https://github.com/openboxes/openboxes
theme:
  name: material
  custom_dir: docs/overrides
  logo: img/logo.svg
  palette:

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.footer
    - navigation.expand
    - navigation.section
    - navigation.index
    - content.code.select
    - content.code.annotate
use_directory_urls: true
copyright: Copyright &copy; 2010-2024, OpenBoxes
extra:
  stylesheet: stylesheets/extra.css
  analytics:
    provider: google
    property: G-4244ZMRC67
markdown_extensions:
  - attr_list
  - admonition
  - footnotes
  - tables
  - toc:
      toc_depth: 1
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
nav:
  - Introduction:
    - About: index.md
    - Benefits: about/benefits.md
    - Considerations: about/considerations.md
    - Release Notes: about/release-notes.md
  - Administrator Guide:
    - Installation:
      - Overview: admin-guide/installation/index.md
      - Requirements: admin-guide/installation/requirements.md
      - Ubuntu:
          - Choose Hosting: admin-guide/installation/ubuntu2204/hosting.md
          - Create Virtual Machine: admin-guide/installation/ubuntu2204/vm.md
          - Install Dependencies: admin-guide/installation/ubuntu2204/ubuntu.md
          - Install Java: admin-guide/installation/ubuntu2204/java.md
          - Install MySQL: admin-guide/installation/ubuntu2204/mysql.md
          - Install Application: admin-guide/installation/ubuntu2204/application.md
          - Install Apache/Nginx: admin-guide/installation/ubuntu2204/webserver.md
          - Deploy Application: admin-guide/installation/ubuntu2204/deployment.md
          - Configuration: admin-guide/installation/ubuntu2204/configuration.md
          - Troubleshooting: admin-guide/installation/ubuntu2204/troubleshooting.md
      - Docker: admin-guide/installation/docker.md
      - Mac OS: admin-guide/installation/macos.md
      - Windows: admin-guide/installation/windows.md
    - Configuration:
      - Overview: configuration/index.md
      - Database: configuration/database.md
      - Email: configuration/email.md
      - OpenBoxes: configuration/application.md
      - Sentry: configuration/sentry.md
      - Advanced: admin-guide/installation/advanced.md
      - Advanced:
        - Tomcat AJP: configuration/ajp.md
        - Apache HTTPS: configuration/https.md
      - Example: configuration/example.md
    - Upgrading: upgrading/index.md
  - User Guide:
    - Getting Started: user-guide/index.md
    - Knowledge Base: user-guide/knowledge-base.md
    - Community Support: user-guide/community-support.md
    - YouTube Channel: user-guide/youtube.md
    - Tutorial Videos: user-guide/tutorials.md
  - Developer Guide:
    - Introduction: developer-guide/index.md
    - Architecture: about/architecture.md
    - Getting Started: developer-guide/getting-started.md
    - Contributing: developer-guide/contributing.md
    - Forking: developer-guide/syncing-a-fork.md
    - Tagging a Release: developer-guide/tagging.md
    - Troubleshooting: developer-guide/troubleshooting.md
    - Releasing:
      - Overview: developer-guide/release/index.md
      - Plan: developer-guide/release/plan.md
      - Develop: developer-guide/release/develop.md
      - Prepare: developer-guide/release/prepare.md
      - Test: developer-guide/release/testing.md
      - Finalize: developer-guide/release/finalize.md
      - Document: developer-guide/release/document.md
      - Publish: developer-guide/release/publish.md
      - Deploy: developer-guide/release/deploy.md
      - Cleanup: developer-guide/release/cleanup.md
    - Hotfixes: developer-guide/hotfix/index.md
  - API Guide:
    - Getting Started: api-guide/getting-started.md
    - Authentication: api-guide/authentication.md
    - Pagination: api-guide/pagination.md
    - Filtering: api-guide/lookup.md
    - Formatting: api-guide/formatting.md
    - Testing:
      - OpenAPI/Swagger: apt-guide/openapi.md
      - Postman: apt-guide/postman.md
    - Core API:
      - Locations: api-guide/core/location.md
      - Identifiers: api-guide/core/identifier.md
      - Internal Locations: api-guide/core/internalLocation.md
      - Localizations: api-guide/core/localization.md
      - Reason Codes: api-guide/core/reasonCode.md
    - Products API:
        - Categories: api-guide/products/category.md
        - Products: api-guide/products/product.md
    - Inbound API:
        - Putaways: api-guide/inbound/putaway.md
        - Receiving: api-guide/inbound/receiving.md
    - Outbound API:
        - Stock Movements: api-guide/outbound/stockMovement.md
        - Stock Movement Items: api-guide/outbound/stockMovementItem.md
        - Stock Movement Status: api-guide/outbound/stockMovementStatus.md
    - Generic API:
      - Overview: api-guide/generic/index.md
      - Standard Actions:
        - Get Resources: api-guide/generic/get-resources.md
        - Get Resource: api-guide/generic/get-resource.md
        - Create Resource: api-guide/generic/create-resource.md
        - Update Resource: api-guide/generic/update-resource.md
        - Delete Resource: api-guide/generic/delete-resource.md
      - Bulk Actions:
        - Create Resources: api-guide/generic/create-resources.md
        - Update Resources: api-guide/generic/update-resources.md
  - Community:
    - Support:
      - Overview: support/index.md


