name: API tests

on:
  pull_request:
    branches: [ develop, 'release/**', 'feature/**']
  push:
    branches: [ develop, 'release/**', 'feature/**' ]

jobs:
  build:
    env:
      SERVER_HOST: https://obdev3.pih-emr.org
      SERVER_PATH: /openboxes
      SERVER_PORT: 443
      API_USERNAME: ${{ secrets.API_USERNAME }}
      API_PASSWORD: ${{ secrets.API_PASSWORD }}

    runs-on: ubuntu-latest

    steps:

    - name: 'Checkout source code'
      uses: actions/checkout@v3

    - uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - uses: actions/cache@v1
      with:
        path: ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'

    - name: 'Run tests against remote REST API'
      run: |
        ./gradlew -x npm_run_bundle test --tests=ProductApiTest -Dserver.host=${{ env.SERVER_HOST }} \
          -Dserver.port=${{ env.SERVER_PORT }} -Dserver.path=${{ env.SERVER_PATH }} \
          -Dusername=${{ env.API_USERNAME }} -Dpassword=${{ env.API_PASSWORD }}
