name: Backend Tests

# Is only runnable via other workflows
on:
  workflow_call:

env:
  JAVA_VERSION: 8

jobs:
  run-backend-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # If we start actively supporting other databases, they should be added here so that we can test against them.
        testdatabase: ["mysql:5.7.44", "mysql:8.0.36", "mariadb:10.3.39"]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{env.JAVA_VERSION}}
          distribution: zulu
          cache: gradle

      # Run all tests against each of the above defined databases. We could split this out and have the matrix run
      # against a separate job that only runs database slice tests so that the rest of the tests run faster, but that
      # complicates our flows and makes things like test coverage reporting more difficult. Because of this, we simply
      # run all the tests together. In the future, if tests are taking too long to run, we can re-evaluate.
      - name: Run All Tests
        run: TEST_DATABASE=${{ matrix.testdatabase }} ./grailsw test-app --non-interactive --no-daemon
