name: On Change

# Runs all tests whenever a commit is pushed to a main branch.
on:
  push:
    branches: [ 'master', 'develop', 'release/**' ]

jobs:
  run-frontend-tests:
    uses: ./.github/workflows/frontend-tests.yml

  run-backend-tests:
    uses: ./.github/workflows/backend-tests.yml
