name: Validate Pull Request Title

# When a PR is created or edited, ensure the title is formatted correctly.
on:
  pull_request:
    types: [opened, edited]

jobs:
  pr-title-validator:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # https://github.com/Esri/calcite-design-system/blob/main/.github/workflows/pr-untruncated.yml
      - name: Validate Pull Request Title
        uses: actions/github-script@v7
        with:
          script: |
            const action = require('${{ github.workspace }}/.github/scripts/validatePullRequestTitle.js')
            await action({github, context, core})
