name: Unit tests

on:
  pull_request:
    branches: [ 'feature/upgrade-to-grails-3.3.10', '0.9.x', 'release/**' ]
  push:
    branches: [ 'feature/upgrade-to-grails-3.3.10', '0.9.x', 'release/**' ]

jobs:
  build:
    env:
      JAVA_TOOL_OPTIONS: -Dstringchararrayaccessor.disabled=true

    runs-on: ubuntu-latest

    steps:

      - name: checkout source
        uses: actions/checkout@v3

      - name: configure java 8
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 8

      - name: configure node 14
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: 'load ~/.grails cache'
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-v3-grails-${{ hashFiles('**/build.gradle') }}
          path: ~/.grails

      - id: grails-sdk
        name: 'load ~/grails-3.3.18 cache'
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-v3-grails-3.3.18-${{ hashFiles('**/build.gradle') }}
          path: ~/grails-3.3.18

      - name: 'load ~/.ivy2/ cache'
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-v3-ivy2-${{ hashFiles('**/build.gradle') }}
          path: ~/.ivy2

      - name: 'load ${{ ''$GITHUB_WORKSPACE'' }}/node_modules cache'
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-v3-node_modules-${{ hashFiles('**/package-lock.json') }}
          path: ${{ github.workspace }}/node_modules

      - name: 'load ~/.npm cache'
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-v3-npm-${{ hashFiles('**/package-lock.json') }}
          path: ~/.npm

      - name: download grails SDK from GitHub (unless cached)
        if: steps.grails-sdk.outputs.cache-hit != 'true'
        run: |
          curl -L https://github.com/grails/grails-core/releases/download/v3.3.18/grails-3.3.18.zip \
               -o /tmp/grails-core.zip
          unzip -o /tmp/grails-core.zip -d ~

        # if this step fails midway through, the next will pick up where it left off
      - continue-on-error: true
        name: grails compile
        run: ~/grails-3.3.18/bin/grails compile

      - name: 'grails test-app -unit'
        run: '~/grails-3.3.18/bin/grails test-app -unit --non-interactive -echoOut -echoErr'

      - name: npm test
        run: npm test
